[package]
name = "Heimdallr"
version = "0.1.0"
authors = [ "HAOYUatHZ <haoyu@protonmail.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
ctrlc = { version = "3.1", features = [ "termination" ] }
env_logger = "0.6"
futures = "0.3"
log = "0.4"
tokio = { version = "0.2", features = [ "full" ] }

[[bin]]
name = "tele_in"
path = "src/bin/tele_in.rs"

[[bin]]
name = "tele_out"
path = "src/bin/tele_out.rs"
