version: '3.4'
services:
  db:
    image: timescale/timescaledb:2.1.0-pg13
    container_name: regnbue_bridge_pq
    restart: always
    volumes:
      - ./data/volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: regnbue_bridge
      POSTGRES_USER: regnbue_bridge
      POSTGRES_PASSWORD: regnbue_bridge_AA9944
